### PR TITLE
Preliminary implementation of async handlers.

### PR DESCRIPTION
**Pull request by BeeWarloc**
Works for common use cases, but a fair bit of refactoring should be applied.

### CODE REVIEW

**Comment by asbjornu** [comment]
It is `xbuild` that is failing. We should probably move the tests to `after_success` so they aren't executed if the build fails.

```c#
Program.cs(26,36): error CS0012: The type `Nancy.DefaultNancyBootstrapper' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Nancy, Version=1.4.1.0, Culture=neutral, PublicKeyToken=null'
```

**Comment by BeeWarloc** [comment]
@asbjornu Yes.. Aslo, does nunit integration exist, so we can see how many tests have actually passed in the travis ui?

Might be I'm just blind, but can't seem to find it anywhere.

**Comment by asbjornu** [comment]
@BeeWarloc No, I don't think any such integration exist. To be honest, I haven't seen it for any other test tool either. Do you have an example of how it might look for a tool that is integrated, if it exists?

**Comment by asbjornu** [comment]
But, perhaps we can use [NUnit-HTML-Report-Generator](/JatechUK/NUnit-HTML-Report-Generator) to generate an HTML report from the `TestResult.xml` that NUnit outputs? Not sure how or if that HTML report would be made available, but it might be worth a shot.

**Pull request merged**
