### PR TITLE
Add Travis build

### PR DESCRIPTION
**Pull request by asbjornu**
This is a work in progress to add an automatic build with [Travis](https://travis-ci.org/).

### CODE REVIEW

**Comment by asbjornu** [comment]
@BeeWarloc Do you know why [AppVeyor is failing](https://ci.appveyor.com/project/Pomona/pomona/build/0.28.3-travis.41.build.6) with `Illegal characters in path`? I'll tackle the problems I discover on Travis as I go along.

**Comment by BeeWarloc** [comment]
I have no idea why AppVeyor fails like that. But I haven't had the time yet to investigate.

Was hoping it just was going to work out of the box :/

**Comment by BeeWarloc** [comment]
@asbjornu Just found the problem. It was pretty obvious..

4dfdde13ac5f3448bbaa4844b49f3140fae6dd5c

**Comment by asbjornu** [comment]
Seems like we won't be able to get a Travis (Linux) build working until GitTools/GitVersion#816 is fixed, which depends on libgit2/libgit2sharp#1298 making its way to a (prerelease) package on NuGet.

**Comment by asbjornu** [comment]
@BeeWarloc All that's left now is to figure out why `Pomona.SystemTests.QueryTests.Query_SelectNullableIntegerInAnonymousType_IsSuccessful` is failing with:

```csharp
The GET request to <http://test/critters?$select=[]+as+this&$top=1> failed with '400 BadRequest': Unexpected parse error!
Error on line 0 character 0 of query:
|/
[] as this
at Pomona.Common.RequestDispatcher+<SendHttpRequestAsync>c__async0.MoveNext () <0x41826290 + 0x00bf3> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x419c9b20 + 0x00038> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x419c9730 + 0x00118> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x419c9580 + 0x000b3> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x418408e0 + 0x00042> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x41840840 + 0x0001f> in <filename unknown>:0 
  at Pomona.Common.RequestDispatcher+<SendRequestInnerAsync>c__async1.MoveNext () <0x418256b0 + 0x003fd> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x419c9b20 + 0x00038> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x419c9730 + 0x00118> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x419c9580 + 0x000b3> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x418408e0 + 0x00042> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x41840840 + 0x0001f> in <filename unknown>:0 
  at Pomona.Common.RequestDispatcher+<SendRequestAsync>c__async2.MoveNext () <0x41824520 + 0x007b7> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x419c9b20 + 0x00038> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x419c9730 + 0x00118> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x419c9580 + 0x000b3> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x418408e0 + 0x00042> in <filename unknown>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () <0x418b61a0 + 0x0001f> in <filename unknown>:0 
  at Pomona.Common.RequestDispatcher.SendRequest (System.String uri, System.String httpMethod, System.Object body, ISerializationContextProvider provider, Pomona.Common.RequestOptions options) <0x418cf0a0 + 0x000ae> in <filename unknown>:0 
  at Pomona.Common.PomonaClient.Get (System.String uri, System.Type type, Pomona.Common.RequestOptions requestOptions) <0x418cef10 + 0x00127> in <filename unknown>:0 
  at Pomona.Common.PomonaClientExtensions.Get[T] (IPomonaClient client, System.String uri, Pomona.Common.RequestOptions requestOptions) <0x418cec60 + 0x00063> in <filename unknown>:0 
  at Pomona.Common.Linq.RestQueryProvider.ExecuteSync[T,TConverted] (System.String uri, QueryProjection queryProjection, System.Func`2 clientSideSelectPart, Pomona.Common.RequestOptions requestOptions) <0x418ce460 + 0x00349> in <filename unknown>:0 
  at Pomona.Common.Linq.RestQueryProvider.Execute[T,TConverted] (System.String uri, QueryProjection queryProjection, System.Func`2 clientSideSelectPart, Pomona.Common.RequestOptions requestOptions, Boolean executeAsync) <0x418ce380 + 0x000a4> in <filename unknown>:0 
  at Pomona.Common.Linq.RestQueryProvider.ExecuteWithClientSelectPart[TServer,TClient] (System.String uri, QueryProjection queryProjection, System.Linq.Expressions.Expression`1 clientSideExpression, Pomona.Common.RequestOptions requestOptions, Boolean executeAsync) <0x41ec8df0 + 0x00083> in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,Pomona.Common.Linq.RestQueryProvider,string,Pomona.Common.Linq.RestQueryableTreeParser/QueryProjection,System.Linq.Expressions.LambdaExpression,Pomona.Common.RequestOptions,bool)
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,System.Type,System.Type,Pomona.Common.Linq.RestQueryProvider,string,Pomona.Common.Linq.RestQueryableTreeParser/QueryProjection,System.Linq.Expressions.LambdaExpression,Pomona.Common.RequestOptions,bool)
  at Pomona.Common.Linq.RestQueryProvider.Execute[T] (Pomona.Common.Linq.RestQueryableTreeParser parser, Boolean executeAsync) <0x418ccf60 + 0x002d5> in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,Pomona.Common.Linq.RestQueryProvider,Pomona.Common.Linq.RestQueryableTreeParser,bool)
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,System.Type,Pomona.Common.Linq.RestQueryProvider,Pomona.Common.Linq.RestQueryableTreeParser,bool)
  at Pomona.Common.Linq.RestQueryProvider.Execute (System.Linq.Expressions.Expression expression, System.Type resultType) <0x418c75f0 + 0x000fe> in <filename unknown>:0 
  at Pomona.Common.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult] (System.Linq.Expressions.Expression expression) <0x418c7560 + 0x0003a> in <filename unknown>:0 
  at Pomona.Common.Linq.QueryableBase`1[T].GetEnumerator () <0x419d6500 + 0x00071> in <filename unknown>:0 
  at System.Collections.Generic.List`1[T]..ctor (IEnumerable`1 collection) <0x4166fa70 + 0x00287> in <filename unknown>:0 
  at System.Linq.Enumerable.ToList[TSource] (IEnumerable`1 source) <0x416f13d0 + 0x00083> in <filename unknown>:0 
  at Pomona.SystemTests.QueryTests.Query_SelectNullableIntegerInAnonymousType_IsSuccessful () <0x41f38d80 + 0x002c2> in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x416af650 + 0x000b7> in <filename unknown>:0 
```

**Comment by BeeWarloc** [comment]
@asbjornu It's green :+1:

**Comment by asbjornu** [comment]
@BeeWarloc Brilliant! 😄

**Pull request merged**
